### ISSUE TITLE
aws binary conflicts with aws-cli binary if both are in path

### ISSUE THREAD

**Issue by petemounce** [aws/aws-sdk-core-ruby#110]
I have both ruby + `aws-sdk-core`, and the AWS CLI executable installed. I'm running windows, with ruby 2.0.x x64.

Because ruby is earlier in my PATH, AWS CLI commands are run by the `aws-sdk-core` gem's `aws` binary.

I can move ruby later in the PATH.

However, it would be nice to not need to. Would it be possible to do one or some of the following?
* rename the aws-sdk-core `aws` binary to something else (like `aws-rb`, which it used to be?)?
* make the `aws` ruby binary be in a separate gem, so I can have the SDK but not the binary if I like?
* something else...?

**Comment by trevorrowe** [comment]
At this point, I'm inclined to not rename the binary. I understand there is an unfortunate conflict for Windows users of both the CLI and the Ruby SDK if they have this executable rb scripts flag enabled. That said, I would prefer for now not to rename the REPL until at least the v1 SDK is not longer being supported. Please feel free to continue the conversation, as I'm open to re-evaluate.
