### ISSUE TITLE
SQS polling

### ISSUE THREAD

**Issue by flah00** [aws/aws-sdk-core-ruby#13]
I've got an SNS subscribed to a SQS. I'd like to poll the queue for messages and act on particular notifications. In v1 I would `#poll` the queue, but there doesn't seem to be an equivalent method to wait for pushed messages...

**Comment by trevorrowe** [comment]
@flah00 I've pushed a branch and opened a pull request to added a sqs long polling utility to the version 2 AWS SDK for Ruby. I would appreciate any feedback on the proposed interface.

https://github.com/aws/aws-sdk-ruby/pull/740

Thanks!
