### ISSUE TITLE
Credentials Hash crashes Instance Requests

### ISSUE THREAD

**Issue by baweaver** [aws/aws-sdk-core-ruby#154]
```
NoMethodError: undefined method `set?' for #<Hash...
from ...gems/aws-sdk-core-2.0.9/lib/aws-sdk-core/plugins/request_signer.rb:88
```

We take a look at the method:

``` ruby
def require_credentials(context)
  if
    context.config.credentials.nil? or
    !context.config.credentials.set?
  then
    msg = 'unable to sign request without credentials set'
    raise Errors::MissingCredentialsError, msg
  end
end
```

If credentials can be set via a hash, which allows you to get access, then why is it that they decidedly crash when you call any method on those objects?

We drop into it:

``` ruby
    85: def require_credentials(context)
 => 86:   binding.pry
    87:   if
    88:     context.config.credentials.nil? or
    89:     !context.config.credentials.set?
    90:   then
    91:     msg = 'unable to sign request without credentials set'
    92:     raise Errors::MissingCredentialsError, msg
    93:   end
    94: end
```

...and take a look into the credentials, and sure enough it's a hash. Hashes have no `set?` method, and as such this needs to be fixed.

There needs to be something done with the set method to detect hash parameters. This isn't Java, and as such I'm not particularly keen on making 15 objects for a single request in a method when parameters will work.

The hacky, dirty fix to the immediate:

``` ruby
cred = context.config.credentials
unless cred || (cred.is_a?(Hash) || cred.set?)
```

...which will dump us into another set of fun of methods being called on hashes. It's completely unnecessary to make a new object to do this, constructors should have enough knowledge to not need to require them.

**Comment by fcarrega** [comment]
Hello, I just encountered the same issue while updating Paperclip and aws-sdk to their latest versions.

I solved it by removing credentials declaration from Rails config file (`application.rb` in my case but they can also be found in environment-specific files such as `production.rb` or `development.rb`).

I also found that credentials were loaded from an `aws.rb` file where `Aws.config` was called, so I also removed this code to be sure that credentials are loaded only once.

Now credentials are automagically loaded from `aws.yml` file (which by the way already existed in our app) and things run smoothly.
