### ISSUE TITLE
Request for Amazon S3 Pre-signed POST support

### ISSUE THREAD

**Issue by skyhighwings** [aws/aws-sdk-core-ruby#173]
It seems that in the transition from version one of the SDK to the current version, the implementation of `success_action_status` as a parameter to S3's `put_object` API call was lost. Is this intentional?

See http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html for reference.

**Comment by alex88** [comment]
:+1:

**Comment by trevorrowe** [comment]
@skyhighwings @kabaka @alex88 I've just submitted a pull-request to the main repository that adds pre-signed post support in v2. I would be interested in feedback: https://github.com/aws/aws-sdk-ruby/pull/752

**Comment by trevorrowe** [comment]
This is part of the public SDK now.
