### ISSUE TITLE
AWS::Record equivalent functionality

### ISSUE THREAD

**Issue by jeffb-stell** [aws/aws-sdk-core-ruby#184]
Copying a previous issue opened against aws-sdk-ruby at

https://github.com/aws/aws-sdk-ruby/issues/651

Are there plans to make an ORM helper class like AWS::Record for v2 Aws:: ?

It would be useful for people developing on Rails.

**Comment by trevorrowe** [comment]
We understand there is interest for this and are evaluating working on one.

**Comment by vitalis** [comment]
:+1:

**Comment by trevorrowe** [comment]
Closing this issue. There will be a new repo opened shortly for the work being done on a DynamoDB ORM. Look for an announcement blog post on http://ruby.awsblog.com/.
