### ISSUE TITLE
DynamoDB does not scale up more than 100% when it can

### ISSUE THREAD

**Issue by innovia** [aws/aws-sdk-core-ruby#186]
it is a new dynamodb feature that does not exist here in the sdk

i get an error: Cannot increase provisioned throughput to more than twice current value

which is not the case anymore cause you do have the ability to scale more than 100%

**Comment by trevorrowe** [comment]
I'm not sure why it would with one SDK and not the other. As I mentioned, the Ruby SDK is not validating or constraining the value client side. Are you perhaps using v1 of the AWS SDK for Ruby?

**Comment by innovia** [comment]
Hi Trevor, I do use the v2 (aws-sdk-core)
here's the relevant code I wrote (you can test it yourself by installing my gem https://rubygems.org/gems/elasticDynamoDb


````ruby
require 'thor'
require 'aws-sdk-core'
.
.
.
def aws_init
    if options[:local]
      ENV['AWS_REGION'] = 'us-east-1'
      say "using local DynamoDB"
      self.ddb = Aws::DynamoDB::Client.new({endpoint: 'http://localhost:4567', api: '2012-08-10'})
    else
      credentials = Aws::Credentials.new(
        self.config['global']['aws-access-key-id'], self.config['global']['aws-secret-access-key-id']
      )

      self.ddb = Aws::DynamoDB::Client.new({
        api: '2012-08-10', 
        region: self.config['global']['region'],
        credentials: credentials
      })  
    end
  end

def update_tables(provisioning)
    provisioning.each do |table, values|
      table_options = {
                  :table_name => table,
                  :provisioned_throughput => {
                                              :read_capacity_units =>  values['reads'],
                                              :write_capacity_units =>  values['writes']
                  }
      }
        
      # if one of the keys for the table contain index merge the options for update table
      indexes = provisioning[table].keys.select { |key| key.match(/index/) }
      if !indexes.empty?
        indexes.each do |index|
          table_options.merge!({ 
                         :global_secondary_index_updates => [{:update => { 
                                                                            :index_name => index,
                                                                            :provisioned_throughput => {
                                                                              :read_capacity_units =>  values[index]['reads'],
                                                                              :write_capacity_units => values[index]['writes'] 
                                                                            }
                                                                          }
                                                              }]
          })
        end
      end

      update_single_table(table_options)
    end

def update_single_table(table_options)
    while true
      ready = check_status(table_options[:table_name])

      if ready
        say "Updating provisioning for table: #{table_options[:table_name]}...", color = :cyan
        begin
          result = self.ddb.update_table(table_options)
        rescue Exception => e
          say "\nUnable to update table: #{e.message}\n", color = :red
          
          if e.message.include?('The requested throughput value equals the current value') || e.message.include?('The requested value equals the current value')
            say "Skipping table update - the requested throughput value equals the current value", color = :yellow
            return         
          end

          dynamo_max_limit_error = 'Only 10 tables can be created, updated, or deleted simultaneously'
          if e.message.include?(dynamo_max_limit_error)
            say "#{dynamo_max_limit_error}\nTable #{table_options[:table_name]} is not ready for update, waiting 5 sec before retry", color = :yellow
            sleep 5          
          end

          say "\nRetrying update on #{table_options[:table_name]}", color = :yellow
          update_single_table(table_options) if e.message.include?('The requested throughput value equals the current value')          
        end
        return
        
      else
        say "Table #{table_options[:table_name]} is not ready for update, waiting 5 sec before retry", color = :yellow
        sleep 5
      end
    end  
  end


````



per AWS Support ticket:

You are correct that it is possible to increase the throughput capacity of your DynamoDB tables to > 2x the current capacity using the console and boto. I have re-created this myself in my environment and confirmed the change is possible. 

Now, the error message you are reporting seems to line up with a restriction that was in place previously. This was previously referenced in the DynamoDB FAQ but is no longer present. This restriction was lifted in the last couple of months, so it's interesting that you seem to have encountered it. 

In the past, in order to overcome this limit you would need to iterate over multiple updateTable() requests to increase the throughput in increments of 100% until you reached your desired figure. 

In order to better understand how you have obtained this error message, could you please let me know the specific SDK and version you are referencing? In addition, if you have any sample code which demonstrates the issue, I'll be happy to take a look at this. 

What I suspect might be happening here is the SDK itself may be returning the error message rather than contacting DynamoDB. Alternatively, it could be something on our side that we need to look deeper into, but in order to do so we will need to capture a specific example. To progress this case, can you please try the following:

1) Ensure you are running the latest release of the relevant SDK 
2) Please try performing a Wire Trace in order to capture the underlying HTTP call and response from the DynamoDB service. This will include a request ID which will allow us to trace the behavior.
3) Please confirm the table name you are encountering this error with. Is this global across all tables/regions, or is it only limited to a single table/region? 
4) Please gather this information and update this case to allow us to follow up. 

With this information we'll be able to further troubleshoot this behavior. If you are able to confirm the SDK and version, I may be able to provide some specific instructions for obtaining this information.

Best regards,

Alastair C. | Sydney Support Centre
Amazon Web Services

**Comment by innovia** [comment]
Hi Trevor

I'm sorry my bad, I was checking against the local dynamodb and that indeed have the limitation but the real dynamodb doesn't

im gonna close this issue

Ami
