### ISSUE TITLE
Error using DynamoDB condition_expression with simple_attributes: false

### ISSUE THREAD

**Issue by kalpitad** [aws/aws-sdk-core-ruby#188]
I'm trying to update all my `Aws::DynamoDB::Client.new.put_item` calls to use `condition_expression` instead of `expected`, as the documentation seems to indicate that the later is on path to being deprecated.  However, after reviewing all the documentation, examples, forum, and StackOverflow threads that I could get my hands on, I am not able to get this to work.  I have configured DynamoDB with `Aws.config[:dynamodb] = {simple_attributes: false}`, because I haven't had the opportunity to convert all my code over yet, and I'm wondering if that is tripping me up.

Here is a simplified view of my current code that is working:
    
    def save_click_to_dynamodb
      Aws::DynamoDB::Client.new.put_item(
        table_name: "Clicks",
        item: assembled_attributes,
        expected: {
          "id" => {exists: false},
          "username" => {exists: false}
        }
      )      
      return true
      rescue Aws::DynamoDB::Errors::ConditionalCheckFailedException
        Rails.logger.error "Aws ConditionalCheckFailedException"
        return false
      rescue => e
        Rails.logger.error "#{Time.now.utc}: Error saving click to DynamoDB. Details: #{e}; #{e.backtrace}"
        raise e
    end

The `Clicks` DynamoDB table has a Hash and Range Type primary key, where the `id` attribute is the Hash key, and the 'username' is the Range key.  My scenario is simple: add a new row to the `Clicks` table, only if a row with the same `id` and `username` doesn't already exist. 

Below is my new code that is not working. The only difference is that I'm replacing the `expected` parameter with `condition_expression` and `expression_attribute_values` parameters.

    def save_click_to_dynamodb
      Aws::DynamoDB::Client.new.put_item(
        table_name: "Clicks",
        item: assembled_attributes,
        condition_expression: "id <> :i AND username <> :u",
        expression_attribute_values: {
          "i" => {n: "#{@id}"},
          "u" => {s: "#{@username}"}
        }
      )      
      return true
      rescue Aws::DynamoDB::Errors::ConditionalCheckFailedException
        Rails.logger.error "Aws ConditionalCheckFailedException"
        return false
      rescue => e
        Rails.logger.error "#{Time.now.utc}: Error saving click to DynamoDB. Details: #{e}; #{e.backtrace}"
        raise e
    end

My result is the following error: `Aws::DynamoDB::Errors::InternalFailure: The request processing has failed because of an unknown error, exception or failure.`  I've also tried using the function `attribute_not_exists` in my expression, but I received the same error.

Thanks in advance for any pointers as to what is going wrong here!

**Comment by trevorrowe** [comment]
Are you still encountering this error? You should not be receiving InternalFailure errors from DynamoDB. Instead, it should be returning an error indicating what was wrong with your request.

Might I suggest posting this question to the AWS DynamoDB forums for support? It would be helpful to have the request-id from the error response. You can get this value from the error object:

```ruby
begin
  # call failing operation
rescue Aws::DynamoDB::Errors::InternalFailure => error
  puts error.context.http_response.headers['x-amzn-requestid']
  #=> "68H8H..."
end
```

Here are the DynamoDB forums:
https://forums.aws.amazon.com/forum.jspa?forumID=131

**Comment by kalpitad** [comment]
Thanks @trevorrowe. I want to understand something -- when you say that I should not be receiving InternalFailure errors, do you mean that that indicates a service failure and is not related to the SDK or use of the SDK? 

Let me try this again tomorrow and get back to you. Thanks!

**Comment by trevorrowe** [comment]
That is correct. The remote end is returning an http 500 response with an error message. This is not an error being generated client-side by the SDK.

**Comment by trevorrowe** [comment]
Closing stale issue. Please re-open if you continue having issues.
