### ISSUE TITLE
No easy way to add tags to RDS instances without the ARN

### ISSUE THREAD

**Issue by petems** [aws/aws-sdk-core-ruby#200]
So from looking at the documentation for the RDS API, there's no helper method to add tags like EC2 has, you have to use the generic `add_tags_to_resource-instance_method` method.

http://docs.aws.amazon.com/sdkforruby/api/Aws/RDS/Client.html#add_tags_to_resource-instance_method

However, I can't seem to easily find a way to get the ARN for a given RDS instance. So right now I have a helper method doing this:

```ruby
def self.get_arn_for_instance(region, db_instance_identifier)
    "arn:aws:rds:#{region}:#{account_number(region)}:db:#{db_instance_identifier}"
  end

  def self.account_number(region)
    iam = ::Aws::IAM::Client.new({region: region})
    iam.get_user.data.user.user_id
  end
```

Which is a bit hacky, and doesn't work if the user in question doesn't have IAM permissions.

Is there another way to add tags to RDS instances using the API?

**Comment by trevorrowe** [comment]
I am not aware of a better mechanism at this time.
