### ISSUE TITLE
Documentation incorrect for Aws resource client.

### ISSUE THREAD

**Issue by maartenvanvliet** [aws/aws-sdk-core-ruby#203]
On e.g. http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Resource.html it says: 
```
client = Aws::Resource.new(region: 'us-west-2')
resource = Aws::S3::Resource.new(client: client)
```
The first line should be 
```
client = Aws::S3::Client.new(region: 'us-west-2')
```
It appears the wrong class is outputted by the documentation plugin, see for the line where it is happening: https://github.com/aws/aws-sdk-core-ruby/blob/793f773de1afcc6515ec35a8a015b9ef9657393a/doc-src/plugins/resources.rb#L78

**Comment by trevorrowe** [comment]
Thanks for reporting the documentation issue. I've committed a fix to the new repository: https://github.com/aws/aws-sdk-ruby/commit/3d3ae4c389795e260a36cb3d374e21218534e7a3
