### ISSUE TITLE
Unable to fetch just the metadata

### ISSUE THREAD

**Issue by chenkirk** [aws/aws-sdk-core-ruby#215]
It seems there's no way to fetch just the metadata in v2 of the sdk.

In v1, S3Object has a [metadata method](http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/S3Object.html#metadata-instance_method).

This seems to be gone in v2. The only thing I can see that's similar is to use S3::Object's [get method](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/ObjectSummary.html#get-instance_method) which unfortunately retrieves the whole object wasting bandwidth.

**Comment by trevorrowe** [comment]
Use the #head_object method.

**Comment by trevorrowe** [comment]
Sorry, to be more clear. Use the head object method of the client class or the #metadata method of S3::Object.

**Comment by chenkirk** [comment]
That works well. Thanks. 

Might I propose a head_object method for the S3::ObjectSummary class in the future?

**Comment by trevorrowe** [comment]
@chenkirk You can also cast a `S3::ObjectSummary` to a `S3::Object` using the `#object` method:

```ruby
s3.bucket('aws-sdk').objects.each do |obj_summary|
  obj = obj_summary.object
  puts obj.metdata.inspect # WARNING : makes one HEAD Object request for each obj in the bucket
end
```

Adding a `#head` method directly to the ObjectSummary class isn't a bad idea.
