### ISSUE TITLE
Adding wait_until support for Elastic Beanstalk

### ISSUE THREAD

**Issue by zabawaba99** [aws/aws-sdk-core-ruby#216]
I'm currently deploying an application using the [Elastic Beanstalk Client](http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticBeanstalk/Client.html).  However, I want my process to wait until the application is fully deployed ( the environment is in a 'ready' state ) and then check the version that is running. 

It'd be great to have a `wait_until` method on the Client that would wait until an environment is in a 'ready' state.

**Comment by trevorrowe** [comment]
Thanks for the feature request. I've moved it over to the public backlog for the v2 SDK.
