### ISSUE TITLE
Warnings: Instance variables not initialized

### ISSUE THREAD

**Issue by miah** [aws/aws-sdk-core-ruby#217]
I'm getting a few warnings around some code I wrote. Seems like aws-sdk-core is missing a few variable initializations.

    vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.29/lib/seahorse/client/http/response.rb:125: warning: instance variable @done not initialized
    vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.0.29/lib/seahorse/client/http/response.rb:134: warning: instance variable @error not initialized

**Comment by trevorrowe** [comment]
Thanks, I've added init statements for each of those.
