### ISSUE TITLE
How to stub content-length of S3 object?

### ISSUE THREAD

**Issue by hasanen** [aws/aws-sdk-core-ruby#220]
I want to test that my code fetch the actual size of file from S3, but can't get stubbing right.

I'm trying to stub `get_object` like this
```ruby
client = Aws::S3::Client.new(stub_responses: true)
client.stub_responses(:get_object, { content_length: 1024 })
puts client.get_object(bucket: 'bucket', key: 'key').content_length
```
but I just get empty line in to console. What I'm missing here? I also tested examples of stubbing errors from https://docs.aws.amazon.com/sdkforruby/api/Aws/ClientStubs.html and those works like expected/documented.

**Comment by trevorrowe** [comment]
Thank you for reporting the issue. I've been able to reproduce this and I have a temporary fix that I will be applying. This will ship with the next patch release of the SDK.  I've also opened a new issue here against the master repo: 

https://github.com/aws/aws-sdk-ruby/issues/823
