### ISSUE TITLE
Examples of DynamoDB Parallel Scan?

### ISSUE THREAD

**Issue by phstc** [aws/aws-sdk-core-ruby#60]
Hi

Are there any examples of [DynamoDB Parallel Scan](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#QueryAndScanParallelScan)?

**Comment by trevorrowe** [comment]
I'm going to close this issue as it appears to be answered and it is not related to the source in this project.  Thanks guys.
